export const FETCH_COMPONENTS_REQUEST = 'FETCH_COMPONENTS_REQUEST';
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';
export const FETCH_COMPONENTS_FAILURE = 'FETCH_COMPONENTS_FAILURE';
