export const UPDATE_COMPONENT_REQUEST = 'UPDATE_COMPONENT_REQUEST';
export const UPDATE_COMPONENT_SUCCESS = 'UPDATE_COMPONENT_SUCCESS';
export const UPDATE_COMPONENT_FAILURE = 'UPDATE_COMPONENT_FAILURE';
export const FETCH_COMPONENT_REQUEST = 'FETCH_COMPONENT_REQUEST';
export const FETCH_COMPONENT_SUCCESS = 'FETCH_COMPONENT_SUCCESS';
export const FETCH_COMPONENT_FAILURE = 'FETCH_COMPONENT_FAILURE';
