export const CREATE_COMPONENT_REQUEST = 'CREATE_COMPONENT_REQUEST';
export const CREATE_COMPONENT_SUCCESS = 'CREATE_COMPONENT_SUCCESS';
export const CREATE_COMPONENT_FAILURE = 'CREATE_COMPONENT_FAILURE';
